--1
CREATE TABLE STUDENTS_2 (
SNUM INTEGER NOT NULL PRIMARY KEY,
SFAM CHAR(20),
SIMA CHAR(10),
SOTCH CHAR(15),
STIP INTEGER DEFAULT(0)
)
--2
ALTER TABLE STUDENTS_2
ADD COURS INTEGER;
ALTER TABLE STUDENTS_2
ADD TELEPHONE CHAR(15);
--3
ALTER TABLE STUDENTS_2
DROP COLUMN COURS

ALTER TABLE STUDENTS_2
DROP COLUMN TELEPHONE
--4
USE [3_Аленников_ЛР_7]
EXEC sp_addtype TELEPHONE, 'CHAR(20)', NULL
--5
CREATE INDEX IN_SFAM ON STUDENTS_2(SFAM)
--6
CREATE TABLE PREDMET_2(
PNUM SMALLINT NOT NULL,
PNAME CHAR(20),
TNUM INTEGER NOT NULL,
HOURS SMALLINT NOT NULL,
COURS TINYINT NOT NULL
)

ALTER TABLE PREDMET_2
ADD PRIMARY KEY(PNUM)

CREATE TABLE TEACHERS_2(
TFAM NCHAR(20),
TIMA NCHAR(20),
TNUM INTEGER NOT NULL,
TOTCH NCHAR(15),
TDATE DATETIME
)

ALTER TABLE TEACHERS_2
ADD PRIMARY KEY(TNUM)

CREATE TABLE USP_2(
UNUM INTEGER NOT NULL,
OCENKA TINYINT,
UDATE SMALLDATETIME,
SNUM INTEGER,
PNUM SMALLINT 
)

ALTER TABLE USP_2
ADD PRIMARY KEY(UNUM)
--7
INSERT INTO STUDENTS_2 
SELECT * FROM [3-Аленников].dbo.STUDENTS WHERE SNUM IN (SELECT SNUM FROM [3-Аленников].dbo.USP WHERE OCENKA = 5)
--8
INSERT INTO STUDENTS_2 
SELECT * FROM [3-Аленников].dbo.STUDENTS WHERE SNUM IN (SELECT SNUM FROM [3-Аленников].dbo.USP WHERE OCENKA < 5)

INSERT INTO PREDMET_2 
SELECT * FROM [3-Аленников].dbo.PREDMET

INSERT INTO TEACHERS_2 
SELECT * FROM [3-Аленников].dbo.TEACHERS

INSERT INTO USP_2 
SELECT * FROM [3-Аленников].dbo.USP
--9
ALTER TABLE TEACHERS_2
ADD FOREIGN KEY (TNUM) REFERENCES PREDMET_2 (TNUM)
ON DELETE CASCADE
ON UPDATE CASCADE

ALTER TABLE PREDMET_2
ADD FOREIGN KEY (PNUM) REFERENCES USP_2 (PNUM)
ON DELETE CASCADE
ON UPDATE CASCADE

ALTER TABLE STUDENTS_2
ADD FOREIGN KEY (SNUM) REFERENCES USP_2 (SNUM)
ON DELETE CASCADE
ON UPDATE CASCADE

--10
ALTER TABLE USP_2
ADD CHECK (UDATE <= GetDate())

--11
ALTER TABLE PREDMET_2
ADD CHECK (PNAME IN ('Физика', 'Химия', 'Математика', 'Философия','Экономика'))