SELECT * FROM TEACHERS WHERE TFAM IN ('Казанко', 'Казанков', 'Козанко')

SELECT COUNT(SFAM) AS 'КОЛ-ВО', STIP  FROM STUDENTS GROUP BY STIP ORDER BY 'КОЛ-ВО' DESC

SELECT * FROM STUDENTS WHERE SNUM IN (SELECT SNUM FROM USP WHERE UDATE = '10/06/1999')

SELECT SNUM, SFAM FROM STUDENTS WHERE SNUM IN(SELECT SNUM FROM USP GROUP BY SNUM HAVING COUNT(OCENKA) > 1)

SELECT UDATE,AVG(OCENKA) as 'СРЕДНЕЕ' FROM USP GROUP BY UDATE HAVING CONVERT(INT,AVG(OCENKA)) = MIN(OCENKA)

SELECT COUNT(SNUM) as 'Количество','Студента сдали предмет','математика' as 'Наименование предмета' FROM USP where PNUM = 2003 GROUP BY OCENKA HAVING OCENKA > AVG(OCENKA)

SELECT * FROM PREDMET WHERE PNUM = (SELECT PNUM FROM PREDMET WHERE PNAME = 'ФИЛОСОФИЯ') - 1

SELECT PNAME FROM PREDMET WHERE PNAME LIKE '%[_]%'