SELECT * FROM TEACHERS WHERE TFAM IN ('Казанко', 'Казанков', 'Козанко')

SELECT COUNT(SFAM) AS 'КОЛ-ВО', STIP  FROM STUDENTS GROUP BY STIP ORDER BY 'КОЛ-ВО' DESC

SELECT * FROM STUDENTS WHERE SNUM IN (SELECT SNUM FROM USP WHERE UDATE = '10/06/1999')

SELECT SNUM, SFAM FROM STUDENTS WHERE SNUM IN(SELECT SNUM FROM USP GROUP BY SNUM HAVING COUNT(OCENKA) > 1)